#!/bin/bash

if [ ! -f .hdw_init ]; then
	echo "Not currently in a valid Heroku-Django Wrapper directory."
	echo "If you have a Heroku-Django Wrapper project, you must be"
	echo "in ../project_name/project_name to use this command."
	exit 1
fi

BASEDIR="$1"
SCRIPTS_DIR=$BASEDIR
PYTHON_SCRIPTS_DIR=$BASEDIR/bin
PROJECTNAME=$(egrep -i "PROJECT NAME: " .hdw_init | awk '{print substr ($0, 15, 256)}')


#removing previous static and templates directories...
echo "deleteting previous..."
rm -r -f -q static
rm -r -f -q templates


#currently only copies because I haven't implemented aything else yet
echo "copying over files..."
cp -r _static static
cp -r _templates templates


echo "Finished building."
exit 0
