#!/bin/bash

BASEDIR=~/bin


if [ "$1" = "create" ]; then
	$BASEDIR/heroku-django/new_project $BASEDIR $2
elif [ "$1" = "delete" ]; then
	$BASEDIR/heroku-django/delete_project $BASEDIR $2
elif [ "$1" = "newapp" ]; then
	$BASEDIR/heroku-django/new_app $BASEDIR $2
elif [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
	python $BASEDIR/heroku-django/bin/help.py
fi

exit 0