#!/bin/bash

if [ ! -f .hdw_init ]; then
	echo "Not currently in a valid Heroku-Django Wrapper directory."
	echo "If you have a Heroku-Django Wrapper project, you must be"
	echo "in ../project_name/project_name to use this command."
	exit 1
fi

python manage.py runserver

ps -ef | egrep runserver
